services:
  api:
    build: .
    expose:
      - 80
    networks:
      - app_network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80" 
    depends_on:
      - api
    networks:
      - app_network
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

networks:
  app_network:
    driver: bridge