services:
  backend-head:
    build: 
      context: .
      dockerfile: dockerfile
      args:
        DEPS_GROUP: prod-back
    ports:
      - "8265:8265"  # Ray dashboard
      - "10001:10001"  # Ray client port
      - "6379:6379"  # Redis port
    command: >
      bash -c ".venv/bin/ray start --head 
      --port=6379 
      --dashboard-port=8265 
      --dashboard-host=0.0.0.0 
      --block"
    environment:
      - RAY_HEAD_IP=head
    networks:
      - ray_network

  backend-app:
    build: 
      context: .
      dockerfile: dockerfile
      args:
        DEPS_GROUP: prod-back
    depends_on:
      - backend-head
    ports:
      - "8000:8000"
    command: bash -c "uv run app/main.py"
    environment:
      - RAY_ADDRESS=ray://head:10001
    networks:
      - ray_network

  frontend-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DEPS_GROUP: prod-front
    depends_on:
      - backend-head
      - backend-app
    ports:
      - "8501:8501"
    command: streamlit run app/frontend.py
    networks:
      - ray_network

networks:
  ray_network:
    driver: bridge
